// Species / cultivar names for the share inventory autocomplete.
// Derived from Shade Trees Nursery 2026 availability (size/grade codes stripped).

export const SPECIES_LIST: string[] = [
  "Acer campestre 'Hedge Maple'",
  "Acer freemani Armstrong",
  "Acer ginnala Flame",
  "Acer ginnala Ruby Slippers",
  "Acer griseum",
  "Acer palm. Bloodgood",
  "Acer palm. Crimson Queen",
  "Acer palm. dis. Inabe Shidare",
  "Acer palm. dis. Viridis",
  "Acer palm. dis.Tamukeyama",
  "Acer plat. Crimson King",
  "Acer plat. Crimson Sentry",
  "Acer Rubrum",
  "Acer rubrum October Glory",
  "Acer rubrum Red Sunset",
  "Acer rubrum Redpointe",
  "Acer rubrum Sun Valley",
  "Acer sacharrum",
  "Aesculus carnea Fort McNair",
  "Amelanchier can Autumn Brilliance",
  "Amelanchier can. Autumn Brilliance",
  "Betula jacquemonti",
  "Betula nigra Heritage",
  "Betula papyrifera Paper Birch",
  "Betula populifolia Whitespire",
  "Buxus koreana Green Velvet",
  "Caragana arborescens Pendula",
  "Carpinus betulus Fastigiata",
  "Carpinus caroliniana",
  "Celtis occidentalis",
  "Cercidiphyllum japonicum",
  "Cercidiphyllum japonicum Pendula",
  "Cercis canadensis",
  "Cercis canadensis Forest Pansy",
  "Cercis canadensis Hearts-A-Gold",
  "Cercis canadensis Lavender Twist",
  "Cercis canadensis Merlot",
  "Cercis canadensis Pink Heartbreaker",
  "Cercis canadensis Rising Sun",
  "Cercis Canadensis Royal White",
  "Cercis canadensis Ruby Falls",
  "Cercis Canadensis Vanilla Twist",
  "Chamaecyparis nootkatensis Pendula",
  "Chamaecyparis obtusa Crippsi",
  "Chamaecyparis obtusa Filicoides",
  "Chamaecyparis obtusa Gracillis",
  "Chionanthus virginicus",
  "Cladrastus lutea Yellowood",
  "Cornus alternifolia",
  "Cornus Constellation",
  "Cornus florida Cherokee Brave",
  "Cornus florida Cherokee Princess",
  "Cornus kousa",
  "Cornus kousa 'Summer Fun' Variegated",
  "Cornus kousa Radiant Rose",
  "Cornus kousa Samaritan Variegated",
  "Cornus kousa Satomi",
  "Cornus kousa Venus",
  "Cornus mas Saffron Sentinel",
  "Cornus Stellar Pink",
  "Cotinus coggyria Royal Purple",
  "Cotoneaster apiculatus pendula",
  "Crataegus viridis Winter King",
  "Cryptomeria japonica Yoshino",
  "Cupressocyparis leylandii",
  "Forsythia x intermedia Lynwood",
  "Fruit Cherry Bing",
  "Fruit Cherry Montmorency",
  "Fruit Fig Brown Turkey",
  "Fruit Fig Celeste",
  "Fruit Malus Espalier 2-Tier",
  "Fruit Malus espalier 3 tier",
  "Fruit Malus Gala",
  "Fruit Malus Golden Delicious",
  "Fruit Malus Honey Crisp",
  "Fruit Malus Macoun",
  "Fruit Malus Mutsu",
  "Fruit Malus Variety",
  "Fruit Malus Ywllow Delicious",
  "Fruit Peach Bailey Hardy",
  "Fruit Peach Contender",
  "Fruit Peach Frost",
  "Fruit Peach Red Haven",
  "Fruit Pear Bartlett",
  "Fruit Pear Bosc",
  "Fruit Pear Espalier 3-tier",
  "Fruit Persimmon Fuyu",
  "Ginkgo biloba Autumn Gold",
  "Ginkgo biloba Princeton Sentry",
  "Gleditsia triacanthos Shademaster",
  "Gleditsia triacanthos Sunburst",
  "Gleditsia triacanthos var. inermis Skyline",
  "Gymnocladus diocious",
  "Halesia carolina Arnold Pink",
  "Hamamelis virginiana",
  "Heptacodium miconoides Tianshan Seven Sun Flower",
  "Hibiscus syriacus Aphrodite",
  "Hibiscus syriacus Blue Chiffon",
  "Hibiscus syriacus Blue Satin",
  "Hibiscus syriacus Diana",
  "Hibiscus syriacus French Cabaret Blush",
  "Hibiscus syriacus French Cabaret Purple",
  "Hibiscus syriacus Lavender Chiffon",
  "Hibiscus syriacus Minerva",
  "Hibiscus syriacus Red Heart",
  "Hibiscus syriacus Tahiti",
  "Hibiscus syriacus White Chiffon",
  "Hibiscus syriacus White Chiffon 5",
  "Hydrangea anomala petiol. trellis",
  "Hydrangea arborescens Annabelle",
  "Hydrangea macro Blushing Bride",
  "Hydrangea macro Endless Summer",
  "Hydrangea macro Summer Crush",
  "Hydrangea paniculata Bobo",
  "Hydrangea paniculata Limelight",
  "Hydrangea paniculata Limelight 5yr",
  "Hydrangea paniculata Little Lime",
  "Hydrangea paniculata Pee Gee",
  "Hydrangea paniculata Pink Diamond",
  "Hydrangea paniculata Pink Diamond 5yr",
  "Hydrangea paniculata Pinky Winky",
  "Hydrangea paniculata Pinky Winky 5yr",
  "Hydrangea paniculata Quick Fire",
  "Hydrangea paniculata Tardiva",
  "Hydrangea paniculata Vanilla Strawberry",
  "Hydrangea paniculata White Diamonds",
  "Hydrangea quercifolia Snow Queen",
  "Hypericum fron. Sunburst",
  "Ilex aquipernyi Dragon Lady",
  "Ilex crenata Steeds",
  "Ilex Nellie Stevens",
  "Ilex verticillata Jim Dandy",
  "Ilex verticillata Red Sprite",
  "Ilex verticillata Southern Gentlemen",
  "Ilex verticillata Southern Gentlemen heavy",
  "Ilex verticillata Winter Red",
  "Ilex x meserveae Blue Maid",
  "Ilex x meserveae Blue Princess",
  "Ilex x meserveae Centenial Girl",
  "Ilex x meserveae Centennial Girl",
  "Juniperus Blue Point",
  "Juniperus chinensis Hetzii Columnaris",
  "Juniperus chinensis Hollywood",
  "Juniperus chinensis Robusta Green",
  "Juniperus chinensis Sea Green",
  "Juniperus virginiana Taylors",
  "Koelreuteria paniculata",
  "Ligustrum ovalifolium",
  "Liquidambar styraciflua",
  "Liquidambar styraciflua Slender Silhouette",
  "Liquidambar styraciflua Worplesdon",
  "Liriodendron tulipifera",
  "Liriodendron tulipifera Emerald City",
  "Magnolia 'Alexandrina'",
  "Magnolia 'Ann'",
  "Magnolia 'Jane'",
  "Magnolia Butterfly",
  "Magnolia loebneri Merrill",
  "Magnolia soulangeana",
  "Magnolia stellata Leonard Messel",
  "Magnolia stellata Royal Star",
  "Magnolia virginiana",
  "Magnolia virginiana Moonglow",
  "Malus Coral Burst",
  "Malus Donald Wyman",
  "Malus Gladiator",
  "Malus Harvest Gold",
  "Malus Louisa Weeping Pink",
  "Malus Perfect Purple",
  "Malus Royal Raindrops",
  "Malus Ruby Tears weeping",
  "Malus sargentina",
  "Metasequoia glyptostroboides",
  "Myrica pennsylvanica",
  "Nyssa sylvatica",
  "Nyssa sylvatica Wildfire",
  "Osmanthus heterophyllus Gulftide",
  "Ostrya virginiana",
  "Picea abies Pendula",
  "Picea glauca Pendula",
  "Picea pungens glauca Fat Albert",
  "Pinus parviflora Glauca",
  "Pinus strobus pendula",
  "Platanus x acerifolia 'Exclamation'",
  "Populus trem. 'Quaking Aspen'",
  "Prunus 'First Blush' Pink Columnar",
  "Prunus amanogawa",
  "Prunus autumnalis",
  "Prunus cerasifera Crimson Pointe",
  "Prunus cerasifera Thundercloud",
  "Prunus incisa 'Little Twist'",
  "Prunus maritima",
  "Prunus Mt St Helens",
  "Prunus myrobolan 'Krauter Vesuvius'",
  "Prunus sargenti columnaris",
  "Prunus schipkaensis",
  "Prunus serrulata Kwanzan",
  "Prunus serrulata Royal Burgundy",
  "Prunus serrulata Snow Goose",
  "Prunus subhirtella Pendula",
  "Prunus subhirtella Snow Fountain",
  "Prunus virginiana Shubert",
  "Prunus x Okame",
  "Prunus yedoensis",
  "Prunus yedoensis Akebono pink",
  "Pyrus calleryana Chanticleer",
  "Quercus acutissima",
  "Quercus alba",
  "Quercus Bi-color 'Swamp White Oak'",
  "Quercus coccinea 'Scarlet Oak'",
  "Quercus macrocarpa Burr Oak",
  "Quercus palustris",
  "Quercus phellos 'Willow Oak'",
  "Quercus robur Regal Prince",
  "Quercus rubra",
  "Quercus velutina",
  "Rosa Rugosa",
  "Rosa Rugosa alba",
  "Rubus nigra",
  "Salix alba Tristis",
  "Salix caprea Pendula",
  "Salix Hakura Nishiki",
  "Salix matsudana tortuosa (Corkscrew)",
  "Stewartia pseudocamellia",
  "Styrax japonicus 'Pink Parisol' Weeping",
  "Styrax japonicus Evening Lights",
  "Styrax japonicus Jap. Snowbell",
  "Styrax japonicus Nightfall weeping",
  "Syringa hyacintheflora Pocahantas",
  "Syringa meyeri Palibin",
  "Syringa patula Miss Kim",
  "Syringa preston James McFarlene",
  "Syringa reticulata Ivory Silk",
  "Syringa vulgaris",
  "Syringa vulgaris Alba",
  "Syringa vulgaris Charles Joly magenta",
  "Taxodium distichum Shawnee Brave",
  "Thuja occidentalis Yellow Ribbon",
  "Thuja plicata Green Giant",
  "Thuja plicata Northern Spire",
  "Tilia americana Redmond",
  "Tilia cordata Greenspire",
  "Tilia tomentosa Sterling Silver",
  "Ulmus Americana 'Princeton Elm'",
  "Vaccinium corym. 'Mini Blues'",
  "Vaccinium corym. Blue Jay",
  "Vaccinium corym. Duke",
  "Viburnum dentatum Chicago Lustre",
  "Viburnum opulus Roseum",
  "Viburnum plicatum tomentosum Mariesii",
  "Viburnum plicatum tomentosum Popcorn",
  "Viburnum plicatum tomentosum Shasta",
  "Viburnum rhytidophillum",
  "Viburnum trilobum",
  "Viburnum trilobum Wentworth",
  "Viburnum x rhytidophylloides Allegheny",
  "Vitex agnus cactus",
  "Vitex Blue Diddley",
  "Wisteria sinensis Amethyst Falls staked",
  "Zelkova seratta Village Green",
  "Zelkova serrata Green Vase",
  "Zelkova serrata Musashino",
]
